alias g='git'
alias ga='git add'
alias gals='git add $(git status -s | cut -c4- | fzf)'
alias gp='git push'
alias gs='git status'
alias gc='git commit'
alias gcl='git clone'
alias gdf='git diff'
alias gdb='g branch -D `g branch --list | fzf`'
alias glog='git log --graph --oneline'
alias griom='git checkout master && git pull origin master && git checkout - && git rebase -i origin/master'
alias gcols='git checkout `git branch --list | fzf`'
alias trls='taskrunner `taskrunner --list | fzf`'
alias cdls='cd `ls | fzf`'

alias update-all='brew update && brew upgrade && brew cleanup && vim-update'
