alias g='git'
alias ga='git add'
alias gp='git push'
alias gs='git status'
alias gc='git commit -m'
alias gcl='git clone'
alias gco='git checkout'
alias glog='git log --graph --oneline'

alias update-all='brew update && brew upgrade && brew cleanup && vim-update'
